//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ClienteId { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
    }
}
