//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int CustomerId { get; set; }
        public int RoomId { get; set; }
        public int HotelId { get; set; }
    
        public Customer Customer { get; set; }
        public Hotel Hotel { get; set; }
        public Room Room { get; set; }
    }
}
